[package]
name = "manifile"
version = "0.0.0"
edition = "2021"
repository = "https://github.com/al8n/manifile"
homepage = "https://github.com/al8n/manifile"
documentation = "https://docs.rs/manifile"
description = "Generic purpose append only manifest file implementation."
license = "MIT/Apache-2.0"
rust-version = "1.56"

[[bench]]
path = "benches/foo.rs"
name = "foo"
harness = false

[features]
default = ["std"]
alloc = []
std = ["thiserror"]
nightly = []
memmap = ["memmap2"]

[dependencies]
bitflags = "2"
crc32fast = "1"
paste = "1"
hashbrown = { version = "0.14", optional = true }
memmap2 = { version = "0.9", optional = true }
rayon = { version = "1", optional = true }
serde = { version = "1", optional = true, features = ["derive"] }
thiserror = { version = "1", optional = true }

[dev-dependencies]
criterion = "0.5"
tempfile = "3"

[profile.bench]
opt-level = 3
debug = false
codegen-units = 1
lto = 'thin'
incremental = false
debug-assertions = false
overflow-checks = false
rpath = false

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
